elParaguayo/qtile-extras

.github/workflows/ci.yml
tox.ini

Apparently merges need to be via PR for codecov to pick them up.

Try codecov

---

.github/workflows/ci.yml
qtile_extras/resources/stravadata/locations.py
qtile_extras/widget/strava.py
tox.ini

No need for so many ImportErrors so add additional dependencies to tox.

Add better handling of widgets in unit tests

---

qtile_extras/widget/alsavolumecontrol.py
test/widget/test_alsawidget.py

Provide more useful feedback to prevent issues like #12.

Add error handling for ALSAWidget

---

qtile_extras/popup/toolkit.py

- Default highlight method changed to "block"
- Better handling of removing keyboard hooks

Changes to toolkit

---

qtile_extras/widget/upower.py
test/widget/conftest.py

NativeName -> NativePath
System bus, not session.

Fix UPowerWidget and test

---

qtile_extras/images.py
test/conftest.py
test/test_images.py

New image object uses image source as a mask and then paints drawer source to the unmasked area. Useful for changing colour
of icons without needing multiple icons.

Add new ImgMask object

---

.github/workflows/ci.yml
tox.ini

Also added matrix tests for 3.8-3.10.

Bump CI to python 3.10

---

qtile_extras/widget/alsavolumecontrol.py

Make ALSAWidget colour configurable

---

qtile_extras/widget/network.py

Adds the font color to the network widget to be able to change the color of the details text. As far as I understand the docs are generated automatically

Add font_colour to the network widget

---

CHANGELOG
qtile_extras/widget/brightnesscontrol.py
qtile_extras/widget/livefootballscores.py
qtile_extras/widget/network.py
qtile_extras/widget/strava.py
qtile_extras/widget/upower.py
test/widget/test_brightness_control.py
test/widget/test_livefootballscores.py
test/widget/test_network.py
test/widget/test_strava.py
test/widget/test_upower.py

Changed to `foreground` to be consistent with qtile widgets.

Deprecate `font_colour` parameter

---

CHANGELOG
MANIFEST.in
setup.py
tox.ini

Need to make sure icons etc are packaged.

Better packaging

---

CHANGELOG
qtile_extras/widget/statusnotifier.py

Fixes bug where menu position is not offset correct when using multiple monitors.
Fixes #88

Fix positioning of StatusNotifier menu

---

CHANGELOG
qtile_extras/widget/globalmenu.py

Fix bug where GlobalMenu is not shown for current window when qtile is restarted.
Fixes #58

Fix GlobalMenu restart bug

---

CHANGELOG
qtile_extras/popup/toolkit.py

Adds better handling of killing popups by suppressing any calls to draw once the window has been killed.

Add finalize method for popups

---

CHANGELOG
qtile_extras/widget/visualiser.py

Add flag to stop multiple visualiser processes

---

CHANGELOG
qtile_extras/widget/decorations.py

Ensure decoration is drawn after the extrawidth, not before it!
Fixes: https://github.com/qtile/qtile/issues/3868

Fix extrawidth with PowerlineDecoration

---

CHANGELOG
qtile_extras/widget/__init__.py
qtile_extras/widget/continuous_poll.py
test/scripts/cpoll.py
test/widget/test_continuous_poll.py

This widget displays lines from a continuously running script. The text will update each time a new line is received.

Add ContinuousPoll widget

---

CHANGELOG
qtile_extras/widget/network.py

- Add ability to check if device is connected to the internet (and show an error if not)
- Add ability to always display SSID text

Two updates to `WiFiIcon`

---

CHANGELOG
qtile_extras/widget/decorations.py

Allows user to override decoration colours.

Override `PowerLineDecoration` colours

---

CHANGELOG
qtile_extras/widget/mixins/__init__.py

Code missed the scenario where user correctly provided a list of padding sizes.
Fixes #137

Fix padding in TooltipMixin

---

docs/conf.py
docs/sphinx_qtile_extras.py
qtile_extras/widget/graph.py
qtile_extras/widget/systray.py

- Limit text when widget is just a compatibility fix
- Add github source links
Let's see if this builds on RTD!

Improvements to docs

---

CHANGELOG
qtile_extras/popup/menu.py
qtile_extras/resources/dbusmenu/__init__.py
qtile_extras/widget/statusnotifier.py

Submenus are not being displayed as there was no callback defined to display the menu.
Fixes #148

Fix StatusNotifier submenu bug

---

CHANGELOG
qtile_extras/widget/alsavolumecontrol.py
test/widget/test_alsawidget.py

Add ability to set icon size in ALSAWidget

---

CHANGELOG
qtile_extras/popup/menu.py
qtile_extras/popup/toolkit.py
qtile_extras/widget/statusnotifier.py

Add:
- Ability to round menu highlighting
- Different font colour for highlighted items
- Ability to set menu icon size
Closes #154

Improvements for StatusNotifier menus

---

qtile_extras/popup/toolkit.py

Ensures that x and y coordinates are relative to the current screen.
Fixes #106

Better positioning of popups

---

CHANGELOG
qtile_extras/popup/toolkit.py
test/popup/test_toolkit.py

Adds ability to position popups relative to:
- any corner of the screen
- any midpoint of the screen edges
- centre of the screen
Fixes #176

Improve popup positioning

---

CHANGELOG
qtile_extras/popup/toolkit.py

PopupImage can now display an alternative image as a highlight method.
Fixes #173

Add highlight image to PopupImage

---

CHANGELOG
qtile_extras/widget/globalmenu.py
qtile_extras/widget/statusnotifier.py

3f74061 introduced some improvements to the StatusNotifier context menus but these enhancements were not reflected in the GlobalMenu widget.
Fixes #172

Fix `GlobalMenu` menus

---

qtile_extras/popup/toolkit.py

Allows popups to automatically close after a fixed period of time. This is useful for transient popups.

Add `hide_on_timeout` to popups

---

CHANGELOG
qtile_extras/widget/globalmenu.py
qtile_extras/widget/livefootballscores.py
qtile_extras/widget/mixins/__init__.py
qtile_extras/widget/statusnotifier.py
test/widget/test_livefootballscores.py

Adds new functionality to the `LiveFootballScores` widget.
Adds:
- New menu to replace popup showing list of matches
- Extended popup to show match information

Extended footballscores

---

qtile_extras/widget/decorations.py

Fixing one bug introduced another...
@jx11r - this should fix the issues you reported in #209
@Crystal4276 - given all the other fixes I've done on RectDecorations for you, can you check that this doesn't break anything for you?!

Fix broken decoration on reload

---

CHANGELOG
qtile_extras/widget/image.py

Forgot to add the line to attach the widget's `drawer` object to the image...
Fixes #212

Fix masked image bug

---

CHANGELOG
qtile_extras/widget/alsavolumecontrol.py
test/widget/test_alsawidget.py

ALSAWidget fixes

---

qtile_extras/widget/alsavolumecontrol.py
qtile_extras/widget/brightnesscontrol.py
qtile_extras/widget/mixins/__init__.py

Using `configurable.ExtraFallback` simplifies some of the logic.

Make progress bar use ExtraFallbacks

---

tox.ini

Add `psutil` and pin `stravalib`.

Change test requirements

---

.github/workflows/ci.yml
CHANGELOG
qtile_extras/images.py
qtile_extras/popup/toolkit.py
qtile_extras/resources/footballscores/matchdict.py
qtile_extras/resources/footballscores/playeraction.py
qtile_extras/resources/stravadata/sync.py
qtile_extras/widget/brightnesscontrol.py
qtile_extras/widget/decorations.py
qtile_extras/widget/mirror.py
qtile_extras/widget/tvheadend.py
scripts/ubuntu_wayland_setup
tox.ini

Qtile has a PR which will have a big impact on qtile-extras:
- Upgrading to support wlroots0.16
- Refactoring the `Drawer` class
This PR ensures compatibility with those updates.
See: https://github.com/qtile/qtile/pull/3985

Updates for qtile compatibility

---

CHANGELOG
qtile_extras/images.py
qtile_extras/widget/decorations.py

Qtile has tidied up backend code so we need to fix imports to match.

Fix drawer imports

---

.readthedocs.yaml
test/scripts/window.py
test/widget/test_global_menu.py
test/widget/test_statusnotifier.py
tox.ini

Issues with qtile packaging are preventing my tests from passing here so let's build against a fork while we agree/fix packaging for qtile.

Build against elParaguayo qtile fork

---

CHANGELOG
qtile_extras/widget/__init__.py
qtile_extras/widget/bluetooth.py

Adding a bluetooth widget to allow you to pair, connect and disconnect devices.
Unfinished at the moment...

Add bluetooth widget

---

CHANGELOG
docs/index.rst
docs/manual/ref/hooks.rst
docs/sphinx_qtile_extras.py
qtile_extras/hook.py
qtile_extras/widget/githubnotifications.py
qtile_extras/widget/livefootballscores.py
qtile_extras/widget/mpris2widget.py
qtile_extras/widget/syncthing.py
qtile_extras/widget/tvheadend.py
qtile_extras/widget/upower.py

Qtile has added the ability for third party apps to define their own hooks so this PR adds custom hooks for a number of widgets.

Adding custom hooks

---

CHANGELOG
qtile_extras/widget/visualiser.py

This may be the fix to the visualiser CPU bug. Needs people to test!

Try to fix visualiser CPU issue

---

docs/sphinx_qtile_extras.py

[docs] Fix default code highlighting

---

.github/workflows/ci.yml
CHANGELOG
qtile_extras/widget/__init__.py
qtile_extras/widget/iwd.py
qtile_extras/widget/mixins/__init__.py
qtile_extras/widget/network.py
test/widget/test_iwd.py

(Draft for now)
Adding an IWD widget which allows scanning of networks and selecting network to join (including password entry).

Add IWD widget

---

.gitignore
.readthedocs.yaml
docs/Makefile
docs/conf.py
docs/requirements.txt
docs/sphinx_qtile_extras.py
test/backend/wayland/conftest.py
test/widget/docs_screenshots/conftest.py
test/widget/docs_screenshots/ss_iwd.py

Add functionality to build widget screenshots dynamically (i.e. same as for qtile).

Widget screenshots

---

CHANGELOG
qtile_extras/widget/__init__.py
qtile_extras/widget/animatedimage.py
test/widget/test_animated_image.py

Widget loops over a list of images to create an animation effect.

Add `AnimatedImage` widget

---

CHANGELOG
qtile_extras/widget/bluetooth.py
qtile_extras/widget/iwd.py
qtile_extras/widget/livefootballscores.py
qtile_extras/widget/mixins/__init__.py
qtile_extras/widget/pulse_volume.py

Fix bug where popup menus ignored config

---

qtile_extras/widget/livefootballscores.py
qtile_extras/widget/mixins/__init__.py

Fix typo.
Remove default opacity value for LiveFootballScores widget.

Change opacity bugs in popup menus

---

CHANGELOG
qtile_extras/layout/decorations/injections.py

ConditionalBorder adjusts the window size based on default value but it should adjust based on the previous border width.

Bugfix ConditionalBorder

---

CHANGELOG
qtile_extras/popup/toolkit.py

Fix highlight border on popup toolkit controls

---

test/widget/test_pong.py
test/widget/test_snake.py

Add game tests

---

qtile_extras/widget/__init__.py
qtile_extras/widget/currentlayout.py
test/widget/docs_screenshots/ss_currentlayout.py

Should reduce config breakages for users.

Add `CurrentLayoutIcon` helper class

---

CHANGELOG
qtile_extras/resources/footballscores/footballmatch.py
qtile_extras/resources/footballscores/league.py
qtile_extras/resources/footballscores/matchdict.py
qtile_extras/resources/footballscores/playeraction.py
qtile_extras/resources/footballscores/utils.py
qtile_extras/widget/livefootballscores.py
test/widget/resources/lfs_data.py
test/widget/test_livefootballscores.py

Not quite ready yet but getting closer. Submitting this as a PR to encourage me to see it through!

Finally update LiveFootballScores for new API
