qtile_extras/popup/menu.py, test/scripts/window.py
This is why we do tests!
Passing a filepath for an icon in the statusnotifier test showed that the menu wasn't handling this correctly.
=> Fix bug in toolkit menuitem

docs/manual/install.rst
I am currently maintaining Qtile package for Fedora in a Copr project since it was retired from the official repositories and trying to get it back (currently waiting for somebody to do a package review).
I am going to do the same for `qtile-extras`.
=> Add installation instructions for Fedora

qtile_extras/widget/alsavolumecontrol.py, tox.ini
Where amixer includes decibel levels in the output, the current regex will fail and so no volume will be recognised.
This PR fixes that by making the regex less strict.
Fixes #33
=> Fix regex bug in ALSAWidget

tox.ini
We're using ReadTheDocs webhook and status on pull requests now so no need for a separate test in CI.
`tox -e docs` is still available for local testing.
=> Remove docs test from CI

qtile_extras/widget/decorations.py, test/widget/test_widget_decorations.py
This PR allows the RectDecoration colour to be specified by the widget's background colour. This is helpful in two scenarios:
1) The same decoration config can be used for multiple widgets
2) Some widget's change colour depending on status so this change can be reflected in the decoration.
=> Allow RectDecoration to inherit colour from widget

CHANGELOG, qtile_extras/widget/statusnotifier.py
If there are no menu items, the widget shouldn't try to create a menu so we exit the function immediately.
=> Better handling of empty menu in StatusNotifier

CHANGELOG, qtile_extras/widget/mixins/__init__.py
I was trying to write a dynamic tooltip for `UPowerWidget` and noticed the tooltip was only showing up once. I figured out that it was because `self._tooltip_timer` still had a value in `_start_tooltip`, which requires it to be falsey. I have updated `_stop_tooltip` to explicitly set `_tooltip_timer` to `None`.
=> Fix tooltip only showing once

CHANGELOG, docs/rtd_requirements.txt
Builds fail with following message "The unauthenticated git protocol on port 9418 is no longer supported".
Replace git clone address with https.
=> Fix docs build error

CHANGELOG, qtile_extras/popup/toolkit.py, test/popup/test_toolkit.py
Ensure that keyboard navigation is disabled when there are no focusable controls.
Fixes #49
=> Better handling of layout initialisation

CHANGELOG, qtile_extras/popup/toolkit.py, test/popup/test_toolkit.py
Previous code did not take account of x and y offsets for multiple monitors so popups were always placed relative the (0, 0) origin.
This PR defaults to placing the window on the current screen but the popup can be placed anywhere by using absolute x and y coordinates.
Fixes #50
=> Fix position of popups on multiple monitor setups

CHANGELOG, qtile_extras/popup/toolkit.py
A commit introduced by https://github.com/qtile/qtile/pull/3647/ changed the keys in the keysyms dictionary to lower case. We therefore need to make sure the configuration for a popup is converted to lower case.
=> Fix toolkit keyboard navigation

CHANGELOG, qtile_extras/widget/wordclock.py
If it's 23 hours and the hour increment is triggered then we get a value of 24 which causes the `datetime.time` conversion to crash as hours must be in the 0 to 23 range.
=> Fix wordclock crash

CHANGELOG, qtile_extras/widget/currentlayout.py
Enable scaling of icon via the `scale` parameter.
Also, disable `use_mask=True` default value i.e. the widget will behaviour identically to the default qtile widget unless a user explicitly sets `use_mask=True`.
Fixes #72
=> Fix CurrentLayoutIcon widget

CHANGELOG, qtile_extras/widget/upower.py, test/widget/test_network.py, test/widget/test_upower.py
This PR makes it behave like all TextBox widgets.
I've also made the network widget tests optional, I don't have iwlib available on Debian and didn't want to build from source.
=> UPower widget doesn't show text if fontsize is unset.

CHANGELOG, qtile_extras/widget/upower.py
Default behaviour is to use standard colours but the PR allows users to override the default behaviour and set a fill colour for when the battery is charging.
Closes #85
=> Add `fill_charge` parameter for UPower widget

CHANGELOG, qtile_extras/widget/upower.py
Reloading config can cause multiple callbacks to be triggered giving undesirable behaviour.
This PR adds code to unsubscribe from signals and disconnect the bus object.
Fixes #92
=> Unsubscribe dbus signals in Upower widget

tox.ini
CI test suite needs this for Wayland tests to pass.
=> Bump pywlroots version to match qtile

CHANGELOG, qtile_extras/widget/network.py, test/widget/test_network.py
Bug didn't allow users to set mouse callbacks on other button press events. This has been fixed along with exposing a `show_text()` command to display the wifi network name.
Fixes #101
=> Fix mouse_callbacks in WifiIcon widget

CHANGELOG, qtile_extras/widget/decorations.py
There was a bug in PowerLineDecoration where additional layers were painted resulting in alpha blending of semi-transparent values.
=> Fix transparency in `PowerLineDecoration`

CHANGELOG, qtile_extras/widget/__init__.py, qtile_extras/widget/systray.py
Systray icons take their back pixmap from the widget background. This is ok when it's a solid bacground colour but decorations have uneven backgrounds.
This PR updates the Systray widget to just use the RectDecoration's fill colour for the background of the icon.
Fixes #108
This needs https://github.com/qtile/qtile/pull/3833 to be merged first.
=> Improve Systray behaviour with RectDecoration

CHANGELOG, qtile_extras/resources/footballscores/footballmatch.py, tox.ini
pytest-cov 4.0.0 dropped `multiprocessing` support which means that tests relying on a `manager` instance may show as uncovered.
=> Pin pytest-cov to 3.0.0

CHANGELOG, qtile_extras/widget/visualiser.py
The Visualiser widget has a bug where, if the user is using a widget decoration, the widget expects a larger image size than it receives from the cava_draw script. This is because it bases the image size on the widget width, rather than the visualiser width.
Fixes #121
=> Fix Visualiser size bug

CHANGELOG, qtile_extras/widget/decorations.py, test/widget/test_widget_decorations.py
This PR allows users to define an `extrawidth` property which will increase the width of the underlying widget. This is useful when the decoration cuts off widget's contents (notably with the `Systray` widget
=> Add `extrawidth` to decorations

CHANGELOG, qtile_extras/widget/decorations.py
Grouped decorations look up their position in the bar. This can cause issues when the widget is inside a WidgerBox.
This PR addresses the issue by only allowing grouping when the widget is in the parent bar (i.e. visible).
Fixes #126
=> Fix IndexError on RectDecoration

CHANGELOG, qtile_extras/widget/decorations.py
When using `use_widget_background` the decoration does not draw correctly after a reload.
=> Fix `RectDecoration` reload bug

qtile_extras/widget/decorations.py
I think you forgot this, it doesn't update the `next_background` color:
=> Fix `next_background` on `PowerLineDecoration`

qtile_extras/widget/livefootballscores.py
Underline extends to width of widget which includes any extra length from the decoration. This PR fixes that so the line is only drawn under the main widget body.
=> Fix underline length in `LiveFootballScores`

CHANGELOG, qtile_extras/widget/network.py
The widget needs to handle more than `TimeoutError` as it can raise an `OSError` if there is no internet at all.
=> WiFi icon internet check fix

CHANGELOG, qtile_extras/resources/visualiser/cava_draw.py, qtile_extras/widget/visualiser.py
Using SharedMemory seemed to result in a segfault when stopping, starting and reloading the widget.
Moving to mmap seems to fix the issue.
This should also fix the memory leak issue.
Fixes #135
Fixes #119
=> Convert `Visualiser` from shared memory to mmap

CHANGELOG, qtile_extras/widget/decorations.py
Mirrors need to draw decorations separately, particularly when using PowerLineDecorations as this looks at the next weidget in the bar for the colouring.
In order to do this, decorations cannot be drawn to the RecordingSurface otherwise mirrors will draw the same decoration. Instead, the decorations are now drawn directly to the window surface.
The PR also adds a new QTEMirror class as the Mirror draw method also needs to be updated as it looks at the parent's length but, as that may already have been modified by a decoration, we have to look at a different attribute.
Fixes #136
=> Fix mirror handling of decorations

CHANGELOG, qtile_extras/widget/globalmenu.py, qtile_extras/widget/statusnotifier.py
d7367da5 passed the positioning of the popup to the toolkit. As such, the StatusNotifier and GlobalMenu widgets no longer need to adjust the position for the current screen.
Fixes #169
=> Fix menu positions

CHANGELOG, qtile_extras/widget/decorations.py
Clipping can only reduce the clipped area. Therefore, when a widget grows, the decoration cannot draw into the larger area.
This issue is fixed by resetting the clipped area before drawing the decoration.
Fixes #168
=> Fix RectDecoration clipping bug

CHANGELOG, qtile_extras/widget/decorations.py
Where a widget inherits a class which has also had widget code injected then an infinite recursion loop can occur when the widget tries to _configure.
We can fix this by removing the injected code for subclasses while the widget is configured and then replace the injected code afterwards.
Fixes #163
=> Fix recursion error with decoration injection

CHANGELOG, qtile_extras/widget/decorations.py
The clipping needs to be applied to the widget's context and not the underlying window's context.
Fixes #174
=> Fix RectDecoration clipping again

CHANGELOG, qtile_extras/widget/livefootballscores.py
Away indicators were in the wrong place when using the PowerLineDecoration as they were placed by reference to the widget's `width`.
=> Fix LiveFootballScores indicator locations

qtile_extras/popup/menu.py, qtile_extras/popup/toolkit.py
Previously this was enabled just for menus but there was no reason for popups not to have the same functionality.
It's disabled by default for popups but enabled for menus.
Fixes #181
=> Add ability to kill popups when pointer leaves

CHANGELOG, docs/manual/how_to/popup.rst, qtile_extras/popup/toolkit.py, test/popup/test_toolkit.py
Adds a new `popup.update_controls` method which allows control values to be updated without having to recreate the whole popup.
Fixes #165
=> Add ability to update popup controls

CHANGELOG, qtile_extras/widget/decorations.py, test/widget/test_widget_decorations.py
The decoration drew lines between grouped widgets. This PR should remove those middle lines.
Fixes #195
Fixes #193
=> Fix `RectDecoration` when not filled

CHANGELOG, qtile_extras/widget/decorations.py
A widget inside a widgetbox is not added to the list of bar widgets and so the PowerLine decoration cannot find the next widget in the bar as its parent is not in the bar.
=> Fix decoration configure inside WidgetBox

CHANGELOG, qtile_extras/widget/analogueclock.py
`AnalogueClock` had a little bug in it which should now be fixed (failed to initialise a variable correctly).
Added ability to fine tune position of clock via new `adjust_x/y` parameters.
Fixes #206
=> Fix and improve `AnalogueClock`

CHANGELOG, qtile_extras/popup/toolkit.py
Popups were not rendering correctly after a mouse focus change leading to artefacts where the popup background was not cleared.
Fixes #217
=> Fix popup redraw bug after mouse focus change

CHANGELOG, qtile_extras/widget/livefootballscores.py, test/widget/resources/lfs_data.py, test/widget/test_livefootballscores.py
Widget has a bug where the summary popup had excess separators whenever there were `teams` or `leagues` that had no current matches.
This PR limits the occasions when the separator is included in the popup.
=> Fix livefootballscores separator bug

qtile_extras/widget/statusnotifier.py
Widget included some code which has since been merged into the main qtile repo so it's redundant here.
=> Remove redundant code in StatusNotifier

qtile_extras/widget/decorations.py
Qtile's `Notify` widget currently has a `_clear` method which is the same name as a method injected by the decoration code. As a result, the `Notify` widget does not render correctly when imported via qtile-extras. We can fix that by renaming the injected method.
Fixes #233
=> Fix decoration issue with `Notify` widget

CHANGELOG, qtile_extras/resources/dbusmenu/__init__.py, qtile_extras/resources/dbusmenu/dbusmenu.py, test/widget/test_statusnotifier.py
Electron apps are no longer using libappindicator to generate StatusNotifierItem icons. This change has resulted in items not being open to introspection which means we need to rely on a default interface specification.
Requires https://github.com/qtile/qtile/pull/4226
=> Update StatusNotifier to fix bug in electron apps

qtile_extras/widget/decorations.py
Fixes a bug where a widget has multiple decorations, one of which is grouped and another which is a `PowerLineDecoration`. The bug arises because the `PowerLineDecoration` does not inherit the `GroupMixin` and, as a result, does not set the `group` attribute. However, when grouped widgets checking grouping, they loop over all decorations and check the `group` attribute. This therefore fails when the loop hits the `PowerLineDecoration`.
This PR fixes the issue by hardcoding the `group` attribute for `PowerLineDecoration` objects.
Fixes #248
=> Fix attribute error in decorations

CHANGELOG, qtile_extras/popup/toolkit.py, qtile_extras/widget/decorations.py, qtile_extras/widget/mirror.py
This PR takes advantage of the new `Drawer.clear_rect` method in qtile to clear a subset of the Drawer area which is required in `PowerLineDecoration.paint_background`. This change removes the requirement for backend specific code meaning that the decorations should work in both X11 and Wayland...
It needs the update to qtile that is provided by https://github.com/qtile/qtile/pull/4396
=> Update `PowerLineDecoration` to use new `clear_rect` method from qtile

CHANGELOG, qtile_extras/widget/decorations.py
1) `RectDecoration` could, in certain situations, cause an issue with  widgets using the `Img` masking behaviour, resulting in just a filled decoration.
2) `RectDecoration` had an issue with the `GroupBox` widget where a border could be drawn when just one group showed.
Fixes https://github.com/elParaguayo/qtile-extras/issues/266
Fixes https://github.com/elParaguayo/qtile-extras/issues/267
=> Fix RectDecoration clash with ImgMask

CHANGELOG, qtile_extras/resources/global_menu/registrar.py, qtile_extras/widget/globalmenu.py, test/widget/test_global_menu.py, tox.ini
This is experimental!
Wayland windows don't have an ID so we can try using the process ID to match windows to their dbus service.
=> Add support for GlobalMenu for wayland

CHANGELOG, qtile_extras/widget/brightnesscontrol.py
Deprecate `widget_width` parameter and use `bar_width` instead. This, in turn, fixes the issue where text is not being centered in the middle of the bar.
=> BrightnessControl fixes

CHANGELOG, qtile_extras/resources/visualiser/cava_draw.py, qtile_extras/widget/visualiser.py
Adds `invert` parameter to the `Visualiser` widget which allows the bars to be drawn from the top of the widget.
The commit also simplifies the drawing of the bars.
=> Add ability to invert visualiser

CHANGELOG, qtile_extras/widget/upower.py
To draw the widget, the code looks up the `fraction` key in the battery's dictionary. However, if draw has been called before this information has been retrieved (as can happen at startup), a KeyError arises.
This PR fixes the issue by initialising the battery with a default value of 50%.
=> Fix `fraction` KeyError in `UpowerWidget`

CHANGELOG, qtile_extras/widget/visualiser.py
Use a threading.Lock object and only release lock once FPS interval has elapsed.
=> Better framerate fix for `Visualiser`

.github/workflows/ci.yml, tox.ini
Keep 3.11 as "main" test for now (e.g. decoration rendering).
=> Add python 3.12 to CI

docs/manual/how_to/popup.rst
Hi, only a small PR here.
I've removed the 'tk.' which is not needed, and I've included the proper imports for the text popup example to work.
=> Updated documentation's example code for Popups

docs/manual/how_to/popup.rst
I'm really sorry, my last PR broke the code block!
Sometimes newlines are important :sweat_smile: 
I didn't even think to view it, since it looked like such a simple update. Lesson learnt, code always breaks lol.
The code block for the section "Updating Controls" doesn't show.
[https://github.com/elParaguayo/qtile-extras/blob/main/docs/manual/how_to/popup.rst#updating-controls](https://github.com/elParaguayo/qtile-extras/blob/main/docs/manual/how_to/popup.rst#updating-controls)
And now it does show.
[https://github.com/sslater11/qtile-extras/blob/documentation/docs/manual/how_to/popup.rst#updating-controls](https://github.com/sslater11/qtile-extras/blob/documentation/docs/manual/how_to/popup.rst#updating-controls)
=> Updated documentation - Added missing newline which prevented code block from showing.

CHANGELOG, qtile_extras/widget/visualiser.py
Setting `hide=False` to the Visualiser prevents the visualiser drawing correctly until the entire bar is redrawn. We fix this by forcing a bar redraw once the cava process has started.
=> Fix bug Visualiser doesn't start when unhidden

qtile_extras/widget/mpris2widget.py
Qtile has just merged https://github.com/qtile/qtile/commit/6552c7359348dbdfb12fff1492b4be793aa560d4 which makes some changes to the Mpris2 widget. This PR ensures compatibility.
Needs: https://github.com/qtile/qtile/pull/4665
=> Update Mpris2 widget for compatibility with main

qtile_extras/widget/snapcast.py
Terminating the snapclient process leaves a zombie process in the process tree. We need to `wait()` for the return code to remove the zombie.
=> Prevent zombie process for SnapCast widget

CHANGELOG, qtile_extras/widget/githubnotifications.py, tox.ini
1) Handle errors when polling github API
2) Expose `update()` method
Fixes #317
=> Two fixes for GithubNotifications

CHANGELOG, qtile_extras/widget/base.py
The bar colour selector expects a volume level <= 100. Some devices allow values > 100 so we need to catch this scenario.
Fixes #302
=> Fix Volume bug where volume > 100

CHANGELOG, qtile_extras/widget/bluetooth.py, qtile_extras/widget/iwd.py, qtile_extras/widget/livefootballscores.py, qtile_extras/widget/mixins/__init__.py, qtile_extras/widget/pulse_volume.py
The popup toolkit has some powerful funcitonality for customising the location of the popup. This PR exposes those methods to exposed commands for widgets using the popup menu. Clicking on widgets retains the default behaviour (menu appears by the widget) but it's also possible to call the command with specific arguments (e.g. binding a key to open IWD's network list in the middle of the screen).
=> Add ability to customise position of widget menus

CHANGELOG, qtile_extras/popup/toolkit.py
Clicking and dragging on these controls will result in the value being updated. An optional callback, `drag_callback`, will be called with the new value when the mouse button is released.
=> Add basic drag functionality to Slider and CircularProgress controls

qtile_extras/popup/toolkit.py
Adds `relative_to=0` to `popup.show()`.
=> Allow popups to be placed at mouse pointer

CHANGELOG, qtile_extras/hook.py, qtile_extras/widget/base.py
Adds `volume_change` and `volume_mute_change` hooks to `ALSAWidget` and `PulseVolumeExtra` (and any widget that inherits from `base._Volume`.
=> Add hooks for Volume widgets

CHANGELOG, qtile_extras/layout/decorations/injections.py
When using a mix of decorated and standard borders, we need to check the type of border before trying to reuse SceneRect objects.
=> Fix border bug

qtile_extras/widget/mixins/__init__.py
Tooltips were crashing on some widgets. Removed unnecessary call to `Popup.clear()`.
=> Fix tooltip bug

CHANGELOG, qtile_extras/resources/dbusmenu/__init__.py, qtile_extras/widget/globalmenu.py, test/widget/test_global_menu.py
Previous menus still had callbacks attached to layout changes. These callbacks need to be removed when finalising the widget.
Closes https://github.com/qtile/qtile/issues/4833
=> Fix GlobalMenu callback bug

qtile_extras/widget/statusnotifier.py
A recent commit to qtile moved some code to different folders. We need to update the imports here to match.
Closes #350
=> Fix StatusNotifer import error

CHANGELOG, qtile_extras/layout/decorations/__init__.py, qtile_extras/layout/decorations/injections.py, qtile_extras/layout/decorations/injections_wayland.py
Where a user did not have wayland libraries installed then loading border decorations would fail as the injections module tried to import some wayland classes. This PR fixes the problem by splitting wayland specific code into a separate module which is only imported if the wayland backend is being run.
=> Fix border decoration bug

CHANGELOG, qtile_extras/widget/alsavolumecontrol.py, qtile_extras/widget/base.py
The pulsevolume widget receives a notification from the server when a new app accesses the sound device. This triggers the callback in the widget but, as the widget does not check to see if the volume has changed, the volume is always displayed.
This PR fixes the issue by only displaying the volume when there is a change.
=> Fix volume widget bug - unnecessary display

CHANGELOG, qtile_extras/widget/groupbox2.py, test/widget/test_groupbox2.py
Rules now allow ability to hide boxes from the widget.
=> Add `visible` option to GroupBox2

test/widget/test_scriptexit.py
Sometimes (Fedora minimal buildroot) the python command isn't available, only python3 command is.
=> Don't hardcode the python executable

CHANGELOG, qtile_extras/widget/mixins/__init__.py
Widget will crash if any padding parameter is `None`.
Fixes #413
=> Fix IWD bug

CHANGELOG, qtile_extras/widget/__init__.py, qtile_extras/widget/currentlayout.py, qtile_extras/widget/decorations.py, test/widget/docs_screenshots/ss_currentlayouticon.py, test/widget/test_currentlayouticon.py
Updated to work with updates in qtile main repo where `CurrentLayout` and `CurrentLayoutIcon` are combined in a single widget.
=> Update CurrentLayout widget

qtile_extras/widget/pulse_volume.py
Add a checkbox to indicate current sink in PulseVolumeWidget
=> PulseVolumeWidget: Add checkbox to indicate current sink

qtile_extras/widget/network.py
qtile has removed the `wlan` widget as `iwlib` is unmaintained. We were using a function from that widget in the `Network` widget so we'll just keep the code for it here.
=> Update network widget after qtile removed wlan
